name = "Fabulously Optimized (antaresalgol custom)"
author = "robotkoer, antaresalgol"
version = "14.1.0-custom.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4d7aabb4f76208c442410ace915c614c5d1f13c3d7c9c189d069da89252485ab"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
